version: "3.6"

services:
  aws-health-notifier:
    image: 311462405659.dkr.ecr.eu-west-1.amazonaws.com/shared/aws-health-notifier:latest
    build:
      context: ./lambda

  trivy:
    image: aquasec/trivy:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./.trivy-cache:/root/.cache
      - ./test-results:/test-results
