name: Validate and Plan Terraform

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

defaults:
 run:
  shell: bash

env:
  TERRAFORM_VERSION: 1.5.7

jobs:
  lint-validate-and-plan:
    name: 'Validate Infrastructure'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Lint Terraform
        id: tf_lint
        run: make lint

      - name: Validate & Plan Terraform
        id: tf_validate
        run: make terraform
